version: '2'
services:
    df-rabbitmq:
        image: rabbitmq:3.7.6-management
        ports:
            - 5672:5672
            - 15672:15672
    df-mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=dataflow
        privileged: true
    df-redis:
        image: redis:latest
        ports:
          - 6379:6379
